package: d2u_staff
version: '1.0.1'
author: Tobias Krais

page:
    title: 'translate:d2u_staff'
    perm: d2u_staff[]
    icon: rex-icon fa-user-circle
    subpages:
        staff: { title: 'translate:d2u_staff', icon: rex-icon fa-user-circle }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: d2u_staff[settings] }

requires:
    redaxo: '>=5.3.0'
    php:
        version: '>=5.6'
    packages:
        d2u_helper: '>=1.3.0'
        tinymce4: '>=0.10'