package: d2u_staff
version: '1.0.3'
author: Tobias Krais

page:
    title: 'translate:d2u_staff'
    perm: d2u_staff[]
    icon: rex-icon fa-user-circle
    subpages:
        staff: { title: 'translate:d2u_staff', icon: rex-icon fa-user-circle }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemclass: pull-right, perm: d2u_staff[settings] }

requires:
    redaxo: >=5.10.0
    packages:
        d2u_helper: '>=1.5.5'