package: d2u_staff
version: '1.2.2'
author: 'Tobias Krais'

page:
    title: 'translate:d2u_staff'
    perm: 'd2u_staff[]'
    icon: rex-icon fa-user-circle
    subpages:
        staff: { title: 'translate:d2u_staff', icon: rex-icon fa-user-circle }
        company: { title: 'translate:d2u_staff_company', icon: rex-icon fa-building-o }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemClass: pull-right, perm: 'd2u_staff[settings]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, itemClass: pull-right, perm: 'd2u_staff[settings]' }

requires:
    php: '>=8.0'
    redaxo: '>=5.10.0'
    packages:
        d2u_helper: '>=1.14.0'
        sprog: '>=1.0.0'
        
installer_ignore:
    - .github