package: d2u_staff
version: '1.0.2'
author: Tobias Krais

page:
    title: 'translate:d2u_staff'
    perm: d2u_staff[]
    icon: rex-icon fa-user-circle
    subpages:
        staff: { title: 'translate:d2u_staff', icon: rex-icon fa-user-circle }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: d2u_staff[settings] }

requires:
    packages:
        d2u_helper: '>=1.4.3'